#!/usr/bin/env bash
# Tier-1 retrieval helper: generates `docs/INDEX.md`, the smallest
# entry point an agent can load to know where to look.
#
# Walks the repo for *.md files (skipping target/, .git/, node_modules/,
# vendored copies) and emits a sorted table:
#
#   path  |  topic  |  related crates  |  status (if ADR)  |  size
#
# Files with YAML frontmatter (Tier 2 — see plan task T1.17) populate
# the topic / related-crates / status columns. Files without
# frontmatter get a placeholder row that surfaces the gap.
#
# Usage:
#   ./scripts/generate-docs-index.sh           # writes docs/INDEX.md
#   ./scripts/generate-docs-index.sh --check   # exit 1 if INDEX.md
#                                              # is stale
#
# Idempotent. The output is deterministic so `--check` is reliable.

set -euo pipefail

# Pin locale so `sort` is byte-stable across macOS / Linux.
# macOS sort folds case under the default locale; CI runners may
# use a different LC_ALL. CONSTITUTION § 16 (legibility): the
# index must be deterministic regardless of host.
export LC_ALL=C
export LANG=C

repo_root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
cd "$repo_root"

mode="${1:-write}"
out="docs/INDEX.md"
tmp=$(mktemp /tmp/convergio-docs-index.XXXXXX.md)
trap 'rm -f "$tmp"' EXIT

# Collect every Markdown file we want to index. (Portable: macOS
# ships bash 3.2 which lacks `mapfile`, so use a plain while loop
# and a temp list file.)
files_list=$(mktemp /tmp/convergio-docs-files.XXXXXX)
trap 'rm -f "$tmp" "$files_list"' EXIT
{
    find . -type f -name "*.md" \
        -not -path "./target/*" \
        -not -path "./.git/*" \
        -not -path "./node_modules/*" \
        -not -path "./dist/*" \
        2>/dev/null \
    | sed 's|^\./||'
    # Always include docs/INDEX.md so the index lists itself even
    # on the very first generation. Otherwise the first pass and
    # the --check second pass disagree.
    echo "docs/INDEX.md"
} | sort -u > "$files_list"

# Pull a single field from a file's YAML frontmatter (if present).
# Frontmatter is between two `---` lines at the very top of the file.
frontmatter_field() {
    local file="$1" field="$2"
    awk -v field="$field" '
        BEGIN { in_fm = 0; depth = 0 }
        NR == 1 && $0 == "---" { in_fm = 1; depth = 1; next }
        in_fm && $0 == "---" { exit }
        in_fm {
            if (match($0, "^" field ":[[:space:]]*")) {
                v = substr($0, RLENGTH + 1)
                gsub(/^[[:space:]]+|[[:space:]]+$/, "", v)
                gsub(/^["'\'']|["'\'']$/, "", v)
                print v
                exit
            }
        }
    ' "$file"
}

# ADR status is parseable from the body (`- Status: accepted`)
# even without YAML frontmatter, since the MADR template uses it.
adr_status() {
    local file="$1"
    awk '
        /^- Status:[[:space:]]/ {
            sub(/^- Status:[[:space:]]+/, "")
            sub(/[[:space:]]*\|.*$/, "")  # drop the `| accepted | ...` template hint
            print
            exit
        }
    ' "$file"
}

# Header
{
    cat <<'HEADER'
# docs INDEX

Auto-generated by `scripts/generate-docs-index.sh`. Do not edit by
hand. CI fails if this file is stale; regenerate with:

```bash
./scripts/generate-docs-index.sh
```

This is the **Tier 1 retrieval entry point** (CONSTITUTION § 16,
plan task T1.16). Agents reading the repo cold should load this
file (~few KB) first, then drill into only the files relevant to
the task. See ADR-0012 (OODA-aware validation) and plan task T4.07
(local RAG) for the deeper retrieval story.

## Index

| Path | Topic | Touches | Status | Lines |
|------|-------|---------|--------|-------|
HEADER
    while IFS= read -r f; do
        topic=$(frontmatter_field "$f" "topic" 2>/dev/null || true)
        touches=$(frontmatter_field "$f" "touches_crates" 2>/dev/null || true)
        status=$(frontmatter_field "$f" "status" 2>/dev/null || true)
        # ADR fallback: parse body if no frontmatter status.
        if [ -z "$status" ] && [[ "$f" =~ ^docs/adr/[0-9]{4}- ]]; then
            status=$(adr_status "$f" 2>/dev/null || true)
        fi
        # Topic fallback: derive from path.
        if [ -z "$topic" ]; then
            case "$f" in
                docs/adr/*) topic="adr" ;;
                docs/plans/*) topic="plan" ;;
                docs/spec/*) topic="spec" ;;
                docs/agents/*) topic="agent-docs" ;;
                CHANGELOG.md|VERSION.md) topic="release" ;;
                README.md) topic="entry" ;;
                AGENTS.md) topic="agent-rules" ;;
                CLAUDE.md|.cursor/*|.github/copilot-instructions.md) topic="agent-bridge" ;;
                CONSTITUTION.md) topic="constitution" ;;
                ARCHITECTURE.md) topic="architecture" ;;
                ROADMAP.md) topic="roadmap" ;;
                CONTRIBUTING.md|CODE_OF_CONDUCT.md|SECURITY.md|LICENSE) topic="governance" ;;
                crates/*/AGENTS.md|crates/*/CLAUDE.md) topic="crate-rules" ;;
                crates/*/README.md) topic="crate-readme" ;;
                examples/*/README.md) topic="example" ;;
                *) topic="-" ;;
            esac
        fi
        # Cell escapes for markdown table.
        topic=${topic//|/\\|}
        touches=${touches//|/\\|}
        status=${status//|/\\|}
        [ -z "$touches" ] && touches="-"
        [ -z "$status" ] && status="-"
        # Skip line-counting INDEX.md itself — its size changes
        # every regeneration, defeating idempotence.
        if [ "$f" = "docs/INDEX.md" ] || [ ! -f "$f" ]; then
            lines="-"
        else
            lines=$(wc -l <"$f" | tr -d ' ')
        fi
        printf '| `%s` | %s | %s | %s | %s |\n' "$f" "$topic" "$touches" "$status" "$lines"
    done < "$files_list"
    cat <<'FOOTER'

## How to add a doc

1. Drop the file in the right folder (`docs/adr/`, `docs/plans/`,
   `crates/<name>/`, etc).
2. Optionally add YAML frontmatter to populate the columns:
   ```yaml
   ---
   topic: validation
   status: accepted
   touches_crates: convergio-durability,convergio-thor
   related_adrs: [0011, 0012]
   ---
   ```
3. Re-run `./scripts/generate-docs-index.sh`.
4. Commit both the new file and the updated `docs/INDEX.md`.

## Why an index, not just `grep`

Agents reading the repo cold cannot afford to load the full corpus
into one context window. CONSTITUTION § 16 makes the legibility
trade-off explicit; this index is the entry point that keeps the
agent's first read under ~2k tokens. Drill into specific docs only
when the task demands it.
FOOTER
} > "$tmp"

if [ "$mode" = "--check" ]; then
    if cmp -s "$tmp" "$out" 2>/dev/null; then
        echo "docs/INDEX.md is current"
        exit 0
    else
        echo "::error::docs/INDEX.md is stale — run ./scripts/generate-docs-index.sh and commit" >&2
        if [ -f "$out" ]; then
            diff -u "$out" "$tmp" | head -40 >&2 || true
        fi
        exit 1
    fi
fi

mv "$tmp" "$out"
trap - EXIT
echo "wrote $out ($(wc -l <"$out" | tr -d ' ') lines)"
